# MinIO credentials
[sources.filesystem.credentials]
aws_access_key_id = "admin"
aws_secret_access_key = "password"
endpoint_url = "http://localhost:9002"
region_name = "eu-central-1"

# Clickhouse credentials
host = "localhost"
port = 9000
http_port = 8123
username = "dltuser"
password = "dltpassword"
secure = 0